-- Catálogo de sexo (CURP: H = Hombre, M = Mujer)
CREATE TABLE gender (
    id_gender   SMALLINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(50)  NOT NULL,
    description VARCHAR(100),
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_gender PRIMARY KEY (id_gender),
    CONSTRAINT uq_gender_name UNIQUE (name)
);
