-- Catálogo de nacionalidades
CREATE TABLE nationality (
    id_nationality SMALLINT GENERATED BY DEFAULT AS IDENTITY,
    name           TEXT  NOT NULL,
    description    TEXT,
    is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_nationality PRIMARY KEY (id_nationality),
    CONSTRAINT uq_nationality_name UNIQUE (name)
);
