-- Catálogo de estado civil
CREATE TABLE marital_status (
    id_marital_status SMALLINT GENERATED BY DEFAULT AS IDENTITY,
    name              TEXT  NOT NULL,
    description       TEXT,
    is_active         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_marital_status PRIMARY KEY (id_marital_status),
    CONSTRAINT uq_marital_status_name UNIQUE (name)
);
