-- Catálogo de entidades federativas (clave INEGI de 2 dígitos)
CREATE TABLE state (
    id_state   SMALLINT GENERATED BY DEFAULT AS IDENTITY,
    cve_ent    CHAR(2)      NOT NULL,
    name       VARCHAR(50)  NOT NULL,
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_state PRIMARY KEY (id_state),
    CONSTRAINT uq_state_cve_ent UNIQUE (cve_ent),
    CONSTRAINT ck_state_cve_ent CHECK (cve_ent ~ '^[0-9]{2}$')
);
