-- Catálogo de municipios (clave INEGI de 3 dígitos, única dentro de cada estado)
CREATE TABLE municipality (
    id_municipality INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_state        SMALLINT     NOT NULL,
    cve_mun         CHAR(3)      NOT NULL,
    name            VARCHAR(100) NOT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_municipality PRIMARY KEY (id_municipality),
    CONSTRAINT fk_municipality_state FOREIGN KEY (id_state) REFERENCES state (id_state),
    CONSTRAINT uq_municipality_state_cve UNIQUE (id_state, cve_mun),
    CONSTRAINT ck_municipality_cve_mun CHECK (cve_mun ~ '^[0-9]{3}$')
);
